const DAN_LEVELS=["Color Belt","1st Dan","2nd Dan","3rd Dan","4th Dan","5th Dan","6th Dan","7th Dan","8th Dan","9th Dan","10th Dan"];
const COLOR_SEQUENCE=[{id:"White",label:"White",belt:"white",stripe:"",tips:[]},{id:"White / Yellow Stripe",label:"White / Yellow Stripe",belt:"white",stripe:"yellow",tips:[]},{id:"White / Yellow Stripe / Yellow Tip",label:"White / Yellow Stripe / Yellow Tip",belt:"white",stripe:"yellow",tips:["yellow"]},{id:"Yellow",label:"Yellow",belt:"yellow",stripe:"",tips:[]},{id:"Yellow / Green Tip",label:"Yellow / Green Tip",belt:"yellow",stripe:"",tips:["green"]},{id:"Green",label:"Green",belt:"green",stripe:"",tips:[]},{id:"Green / Blue Tip",label:"Green / Blue Tip",belt:"green",stripe:"",tips:["blue"]},{id:"Blue",label:"Blue",belt:"blue",stripe:"",tips:[]},{id:"Blue / Brown Tip",label:"Blue / Brown Tip",belt:"blue",stripe:"",tips:["brown"]},{id:"Brown",label:"Brown",belt:"brown",stripe:"",tips:[]},{id:"Brown / Red Tip",label:"Brown / Red Tip",belt:"brown",stripe:"",tips:["red"]},{id:"Red",label:"Red",belt:"red",stripe:"",tips:[]},{id:"Red / Black Tip",label:"Red / Black Tip",belt:"red",stripe:"",tips:["black"]},{id:"Red / Black Stripe",label:"Red / Black Stripe",belt:"red",stripe:"black",tips:[]},{id:"Red / Black Stripe / Black Tip",label:"Red / Black Stripe / Black Tip",belt:"red",stripe:"black",tips:["black"]}];
const TIP_SEQUENCE=["Yellow","Green","Blue","Brown","Red","Black"];
const DAN_TIP_STAGES=TIP_SEQUENCE.flatMap(c=>[{id:`${c} Tip 1`,label:`${c} Tip 1`,color:c.toLowerCase(),count:1},{id:`${c} Tip 2`,label:`${c} Tip 2`,color:c.toLowerCase(),count:2}]);
let currentSet=[],currentIndex=0,currentFront="korean";const $=id=>document.getElementById(id);
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2)}function esc(v){return String(v||"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[ch]))}function danNumber(d){return d==="Color Belt"?0:parseInt(d,10)||0}
function stagesForDan(dan){if(dan==="Color Belt")return COLOR_SEQUENCE.map(s=>({id:s.id,label:s.label}));return DAN_TIP_STAGES.map(s=>({id:s.id,label:s.label}))}
function visualFor(dan,stageId){if(dan==="Color Belt"){const s=COLOR_SEQUENCE.find(x=>x.id===stageId)||COLOR_SEQUENCE[0];return{beltColor:s.belt,stripeColor:s.stripe,tips:s.tips.join(",")}}const n=danNumber(dan),danTips=Array(n).fill("yellow"),s=DAN_TIP_STAGES.find(x=>x.id===stageId)||DAN_TIP_STAGES[0],sectionTips=Array(s.count).fill(s.color);return{beltColor:"black",stripeColor:"",tips:danTips.concat(sectionTips).join(",")}}
function normalizeCard(c){let dan=c.danLevel||c.danDesignation||"Color Belt";if(dan==="None / Color Belt"||dan==="")dan="Color Belt";let stage=c.stage||c.beltSection||c.rank||"White";if(/dan/i.test(stage))stage="Yellow Tip 1";if(dan!=="Color Belt"&&COLOR_SEQUENCE.some(s=>s.id===stage))stage="Yellow Tip 1";if(!stagesForDan(dan).some(s=>s.id===stage))stage=stagesForDan(dan)[0].id;const visual=visualFor(dan,stage);return{id:c.id||uid(),korean:c.korean||"",english:c.english||"",pronunciation:c.pronunciation||"",notes:c.notes||"",category:c.category||"",danLevel:dan,stage:stage,beltColor:visual.beltColor,stripeColor:visual.stripeColor,tips:visual.tips,status:c.status||"new"}}
function getCards(){const raw=localStorage.getItem("tkdCardsV32")||localStorage.getItem("tkdCardsV31")||localStorage.getItem("tkdCardsV3")||localStorage.getItem("tkdCardsV23")||localStorage.getItem("tkdCardsV22")||localStorage.getItem("tkdCardsV2")||localStorage.getItem("cards")||"[]";try{return JSON.parse(raw).map(normalizeCard)}catch(e){return[]}}function setCards(cards){localStorage.setItem("tkdCardsV32",JSON.stringify(cards.map(normalizeCard)))}
function initOptions(){$("danLevel").innerHTML=DAN_LEVELS.map(d=>`<option value="${d}">${d}</option>`).join("");$("studyDanFilter").innerHTML=`<option value="__all">All Dan Levels</option>`+DAN_LEVELS.map(d=>`<option value="${d}">${d}</option>`).join("");$("savedDanFilter").innerHTML=`<option value="__all">All Top Levels</option>`+DAN_LEVELS.map(d=>`<option value="${d}">${d}</option>`).join("");updateStageOptions();rebuildStageFilters()}
function updateStageOptions(){const dan=$("danLevel").value;$("stage").innerHTML=stagesForDan(dan).map(s=>`<option value="${esc(s.id)}">${esc(s.label)}</option>`).join("");updatePreview();$("rankHelp").textContent=dan==="Color Belt"?"Color Belt uses the full colored belt progression.":"Dan levels use the 1-tip / 2-tip structure for each tip color."}
function updatePreview(){const v=visualFor($("danLevel").value,$("stage").value);$("beltPreview").innerHTML=beltHtml(v)}
function allStageOptionsForFilter(dan){if(dan==="__all")return[...COLOR_SEQUENCE.map(s=>({id:s.id,label:s.label})),...DAN_TIP_STAGES.map(s=>({id:s.id,label:s.label}))];return stagesForDan(dan)}
function fillStageSelect(id,dan,label){const old=$(id).value||"__all",seen=new Set(),opts=[];allStageOptionsForFilter(dan).forEach(s=>{if(!seen.has(s.id)){seen.add(s.id);opts.push(s)}});$(id).innerHTML=`<option value="__all">${label}</option>`+opts.map(s=>`<option value="${esc(s.id)}">${esc(s.label)}</option>`).join("");if([...$(id).options].some(o=>o.value===old))$(id).value=old}
function rebuildStageFilters(){fillStageSelect("studyStageFilter",$("studyDanFilter").value||"__all","All Belt / Tip Stages");fillStageSelect("savedStageFilter",$("savedDanFilter").value||"__all","All Color / Tip Stages")}
function setScreen(name){["study","add","saved","stats"].forEach(s=>$(`${s}Screen`).classList.toggle("active",s===name));document.querySelectorAll(".tab-btn").forEach(b=>b.classList.toggle("active",b.dataset.screen===name));if(name==="saved")renderGroupedCards();if(name==="stats")renderStats()}
function beltHtml(c){let html=`<div class="belt" style="background:${esc(c.beltColor||"white")}">`;if(c.stripeColor)html+=`<div class="stripe" style="background:${esc(c.stripeColor)}"></div>`;(c.tips||"").split(",").map(x=>x.trim()).filter(Boolean).forEach((tip,i)=>{html+=`<div class="tip" style="background:${esc(tip)};left:${i*14}px"></div>`});return html+"</div>"}
function saveCard(){const cards=getCards(),id=$("editId").value||uid(),idx=cards.findIndex(c=>c.id===id),v=visualFor($("danLevel").value,$("stage").value);const card={id,korean:$("korean").value.trim(),english:$("english").value.trim(),pronunciation:$("pronunciation").value.trim(),notes:$("notes").value.trim(),category:$("category").value.trim(),danLevel:$("danLevel").value,stage:$("stage").value,beltColor:v.beltColor,stripeColor:v.stripeColor,tips:v.tips,status:idx>=0?cards[idx].status:"new"};if(!card.korean||!card.english){alert("Please enter both the Korean term and English meaning.");return}if(idx>=0)cards[idx]=card;else cards.push(card);setCards(cards);$("saveMessage").textContent=`Saved: ${card.korean} — ${card.english}`;clearForm(false);refreshAll(id);setScreen("saved")}
function clearForm(clearMsg=true){["editId","korean","english","pronunciation","notes","category"].forEach(id=>$(id).value="");$("danLevel").value="Color Belt";updateStageOptions();if(clearMsg)$("saveMessage").textContent=""}
function editCard(id){const c=getCards().find(x=>x.id===id);if(!c)return;$("editId").value=c.id;$("korean").value=c.korean;$("english").value=c.english;$("pronunciation").value=c.pronunciation;$("notes").value=c.notes;$("category").value=c.category;$("danLevel").value=c.danLevel;updateStageOptions();$("stage").value=c.stage;updatePreview();setScreen("add")}
function deleteCard(id){if(!confirm("Delete this card?"))return;setCards(getCards().filter(c=>c.id!==id));refreshAll()}
function filteredCards(){const dan=$("studyDanFilter").value,stage=$("studyStageFilter").value;return getCards().filter(c=>(dan==="__all"||c.danLevel===dan)&&(stage==="__all"||c.stage===stage))}
function rebuildStudySet(keepId=null){currentSet=filteredCards();if($("studyOrder").value==="random")currentSet=currentSet.slice().sort(()=>Math.random()-.5);if(!currentSet.length){$("cardPicker").innerHTML="<option>No cards in this section</option>";currentIndex=0;renderStudyCard();return}if(keepId){const f=currentSet.findIndex(c=>c.id===keepId);currentIndex=f>=0?f:0}else currentIndex=Math.min(currentIndex,currentSet.length-1);$("cardPicker").innerHTML=currentSet.map((c,i)=>`<option value="${i}">${esc(c.korean)} — ${esc(c.english)}</option>`).join("");$("cardPicker").value=String(currentIndex);setFrontSide();renderStudyCard()}
function setFrontSide(){const m=$("startSide").value;currentFront=m==="random"?(Math.random()>.5?"korean":"english"):m}
function renderStudyCard(){$("flashcard").classList.remove("flipped");if(!currentSet.length){$("frontBelt").innerHTML="";$("backBelt").innerHTML="";$("frontText").textContent="No cards";$("backText").textContent="Add cards or choose another section";$("backExtra").textContent="";$("counter").textContent="No cards in this section";return}const c=currentSet[currentIndex];$("frontBelt").innerHTML=beltHtml(c);$("backBelt").innerHTML=beltHtml(c);$("frontText").textContent=currentFront==="korean"?c.korean:c.english;$("backText").textContent=currentFront==="korean"?c.english:c.korean;const extras=[];if(c.pronunciation)extras.push(`Pronunciation: ${c.pronunciation}`);if(c.notes)extras.push(c.notes);$("backExtra").textContent=extras.join(" • ");$("counter").textContent=`Card ${currentIndex+1} of ${currentSet.length} — ${c.danLevel} / ${c.stage}`;$("cardPicker").value=String(currentIndex)}
function nextCard(){if(!currentSet.length)return;currentIndex=(currentIndex+1)%currentSet.length;setFrontSide();renderStudyCard()}function prevCard(){if(!currentSet.length)return;currentIndex=(currentIndex-1+currentSet.length)%currentSet.length;setFrontSide();renderStudyCard()}function flipCard(){$("flashcard").classList.toggle("flipped")}function markStatus(status){if(!currentSet.length)return;const id=currentSet[currentIndex].id,cards=getCards(),idx=cards.findIndex(c=>c.id===id);if(idx>=0){cards[idx].status=status;setCards(cards);refreshAll(id)}}
function savedFilteredCards(){const dan=$("savedDanFilter").value,stage=$("savedStageFilter").value;return getCards().filter(c=>(dan==="__all"||c.danLevel===dan)&&(stage==="__all"||c.stage===stage))}
function renderGroupedCards(){const cards=savedFilteredCards();$("cardCountBadge").textContent=getCards().length;if(!cards.length){$("groupedCardList").innerHTML='<div class="empty-list">No saved cards match this filter.</div>';return}const byDan={};cards.forEach(c=>{byDan[c.danLevel]??={};byDan[c.danLevel][c.stage]??=[];byDan[c.danLevel][c.stage].push(c)});$("groupedCardList").innerHTML=DAN_LEVELS.filter(d=>byDan[d]).map(d=>`<div class="group"><div class="group-title">${esc(d)}</div>`+stagesForDan(d).filter(s=>byDan[d][s.id]).map(s=>`<div class="subgroup"><div class="subgroup-title">${esc(s.label)} (${byDan[d][s.id].length})</div>${byDan[d][s.id].map(cardHtml).join("")}</div>`).join("")+`</div>`).join("")}
function cardHtml(c){return `<div class="card-item"><strong>${esc(c.korean)} — ${esc(c.english)}</strong><small>${esc(c.danLevel)} • ${esc(c.stage)} • ${esc(c.category||"No category")} • ${esc(c.status||"new")}</small><div class="card-actions"><button class="secondary" onclick="editCard('${c.id}')">Edit</button><button class="warning" onclick="deleteCard('${c.id}')">Delete</button></div></div>`}
function renderStats(){const cards=getCards();if(!cards.length){$("statsContent").innerHTML='<div class="empty-list">No cards yet.</div>';return}$("statsContent").innerHTML=`<h3>Overall</h3><div class="stats-grid">${statCards({"All Cards":cards})}</div><h3>By Dan</h3><div class="stats-grid">${statCards(groupStats(cards,c=>c.danLevel))}</div><h3>By Belt / Tip Stage</h3><div class="stats-grid">${statCards(groupStats(cards,c=>c.stage))}</div><h3>By Category</h3><div class="stats-grid">${statCards(groupStats(cards,c=>c.category||"No category"))}</div>`}
function groupStats(cards,fn){const g={};cards.forEach(c=>{const k=fn(c);g[k]??=[];g[k].push(c)});return g}function statCards(groups){return Object.keys(groups).map(name=>{const cards=groups[name],t=cards.length,m=cards.filter(c=>c.status==="mastered").length,p=cards.filter(c=>c.status==="practice").length,u=t-m-p,mp=Math.round(m/t*100),pp=Math.round(p/t*100),up=100-mp-pp,pie=`conic-gradient(var(--green) 0 ${mp}%, var(--gold) ${mp}% ${mp+pp}%, var(--gray) ${mp+pp}% 100%)`;return `<div class="stat-card"><h4>${esc(name)} (${t})</h4><div class="pie-row"><div class="pie" style="background:${pie}"></div><div class="legend"><span><i class="dot green"></i>Know It: ${m} (${mp}%)</span><span><i class="dot gold"></i>Need Practice: ${p} (${pp}%)</span><span><i class="dot gray"></i>Unmarked: ${u} (${up}%)</span></div></div></div>`}).join("")}
function refreshAll(keepId=null){rebuildStageFilters();rebuildStudySet(keepId);renderGroupedCards();renderStats()}function setupSwipe(){let x=0;$("flashcard").addEventListener("touchstart",e=>{x=e.changedTouches[0].screenX},{passive:true});$("flashcard").addEventListener("touchend",e=>{const dx=e.changedTouches[0].screenX-x;if(Math.abs(dx)<55)return;dx<0?nextCard():prevCard()},{passive:true})}
function init(){initOptions();refreshAll();document.querySelectorAll(".tab-btn").forEach(b=>b.addEventListener("click",()=>setScreen(b.dataset.screen)));$("danLevel").addEventListener("change",updateStageOptions);$("stage").addEventListener("change",updatePreview);$("saveBtn").addEventListener("click",saveCard);$("clearBtn").addEventListener("click",()=>clearForm(true));$("studyDanFilter").addEventListener("change",()=>{rebuildStageFilters();rebuildStudySet()});$("studyStageFilter").addEventListener("change",()=>rebuildStudySet());$("studyOrder").addEventListener("change",()=>rebuildStudySet());$("savedDanFilter").addEventListener("change",()=>{rebuildStageFilters();renderGroupedCards()});$("savedStageFilter").addEventListener("change",renderGroupedCards);$("startSide").addEventListener("change",()=>{setFrontSide();renderStudyCard()});$("cardPicker").addEventListener("change",()=>{currentIndex=Number($("cardPicker").value)||0;setFrontSide();renderStudyCard()});$("prevBtn").addEventListener("click",prevCard);$("nextBtn").addEventListener("click",nextCard);$("flipBtn").addEventListener("click",flipCard);$("flashcard").addEventListener("click",flipCard);$("knowBtn").addEventListener("click",()=>markStatus("mastered"));$("practiceBtn").addEventListener("click",()=>markStatus("practice"));setupSwipe();if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js")}
init();